### ISSUE TITLE
Pam u2f for GDM

### ISSUE THREAD

**Issue by Spindel** [Yubico/pam-u2f#15]
So,
  What's missing for me to use this is a way of adding pam_u2f to GDM without making the whole system lock up.

Adding it as sufficient to pam, will let you get it up and running, and you can log in via gdm/login/sudo.

Adding it as requisite for some reason causes repeated failures, and it won't move further.  

What's the recommended config to require token + password to log in on a desktop environment?

**Comment by a-dma** [comment]
What kind of failures are you experiencing?

I can get it up and running on Jessie and it seems to be working reliably.
I'm adding a rule at the end of `gdm-password` and both `requisite` and `required` seem to work.

**Comment by Spindel** [comment]
On fedora, you have to add it before the Password include stack ( as system-password is Requisite marked ) and it appears to lock me out when I try it in u2f => password order.  ( I get three instant-failures )

**Comment by a-dma** [comment]
I have installed Fedora and done some testing.

The module works fine for me. I have added the rule to the end of `gdm-password` as stated before.
The only "problematic" behavior I have noticed is if you add the rule at the beginning of the file and no u2f device is plugged in when you attempt login. This is because the u2f module is constantly accessed and repeatedly returns an error failing to discover devices, but as soon as you plug a device in, the following request succedes and the module waits for a touch event (and a password afterwards).

I'm not sure at this point what could be, do you have any other custom modification to the system?
My advice here would be to install `pamtester`, enable debug mode on the u2f module and do some debugging. You can use pamtester like this

'' $ pamtester gdm-password adma authenticate ''

you should be able to see what's going wrong.
