### ISSUE TITLE
Feature request: LDAP support

### ISSUE THREAD

**Issue by mhalano** [Yubico/pam-u2f#210]
The idea of LDAP support in pam-u2f is to get the public keys optionally from an LDAP object (instead of just a file, which could be hard to keep in sync). The `pam-yubico` seems already have options for that, but of course it doesn't use U2F/FIDO2 technology, which I think it's simpler to deal with.

**Comment by martelletto** [comment]
Sounds interesting, but unfortunately out of pam-u2f's scope, which is to be as simple as possible and local by default. We could of course broaden that scope, but it would take a massive use case to justify the added complexity.

-p.

**Comment by mhalano** [comment]
It could be at least added an option to get the public key from a command return, so it could be executed a command to get the public key from an LDAP directory or other external source, not just a file. I think the use case is to allow to implement a passwordless login using FIDO2, like Windows do, but with Linux. I just don't know if LDAP is a main component of the solution.

**Comment by martelletto** [comment]
The problem is that, by doing so, you're predicating the operation (and to a considerable extent, the security) of pam-u2f on said external tool. While it does address certain use cases, it runs contrary to pam-u2f's core tenets. Local passwordless login is possible through the 'pinverification' and 'userverification' options (on authenticators that understand these options).
