### ISSUE TITLE
Test if existing token corresponds to key

### ISSUE THREAD

**Issue by OJFord** [Yubico/pam-u2f#220]
I apologise if this is already possible and I just haven't been able to work out how (but perhaps if so the issue could be 'document how...'?).

I'd like to be able to test if a key is already registered for a given (or current) user - i.e. does one of the tokens in `/etc/u2f_mappings` (or a given file) correspond to it?

My main use case is to make setup easier/documented as code - if not exists, generate one and store - but it could also be useful in verifying to which key stored tokens belong.

**Comment by LDVG** [comment]
Short answer is that, by design, the only way to test whether an authenticator/key contains a specific credential is by attempting authentication with it (discoverable/resident credentials aside). This may in turn require a test of user presence or some form of user verification (such as a PIN). You may find it easier to have your setup scripts always generate new credentials.

That said, you might find tools like `pamtester` helpful if you would still like to pursue this. This would require a suitable PAM service to test with, and you'd have to iterate through every user present in your `authfile`.

**Comment by OJFord** [comment]
I see, thanks. I'll have to re-think this a bit, since always generating new credentials would mean the list grows each time - not being able remove the previously added token(s) for that key (without also removing any others).
