### ISSUE TITLE
install on peppermint os

### ISSUE THREAD

**Issue by HUNDRETHMONKEY** [Yubico/pam-u2f#275]
**What version of libfido2 are you using?**
not sure
**What operating system are you running?**
Peppermint OS
**What application are you using in conjunction with libfido2?**
fred@fred-Aspire-one-1-132 ~ $ pamu2fcfg > ~/.config/Yubico/u2f_keys
getlogin: No such device or address
fred@fred-Aspire-one-1-132 ~ $ 

**How does the problem manifest itself?**

**Is the problem reproducible?**
all the time
**What are the steps that lead to the problem?**
I am trying to set up Yubikey on my chrombook
**Does the problem happen with different authenticators?**
I don;t know

**Please include the output of `fido2-token -L`.**
?????
<details>
<summary><code>fido2-token -L</code></summary>
<br>
<pre>
$ fido2-token -L

</pre>
</details>

**Please include the output of `fido2-token -I`.**

<details>
<summary><code>fido2-token -I</code></summary>
<br>
<pre>
$ fido2-token -I &lt;device&gt;

</pre>
</details>

**Please include the output of `FIDO_DEBUG=1`.**

<details>
<summary><code>FIDO_DEBUG=1</code></summary>
<br>
<pre>
$ export FIDO_DEBUG=1
$ &lt;command1&gt;
$ &lt;command2&gt;
(...)
$ &lt;commandn&gt;

</pre>
</details>

**Comment by LDVG** [comment]
Hi,

This looks like a [problem that was fixed in pam-u2f v1.0.5 ](https://github.com/Yubico/pam-u2f/pull/44)(released 16 Apr 2018). I **strongly** recommend upgrading to a later version.

You should be able to confirm your pam-u2f version by running `pamu2fcfg --version`. You _may_ also be able to bypass this problem by manually specifying the user name with the `--username` argument.
