### ISSUE TITLE
Can only authenticate when using PIN verification

### ISSUE THREAD

**Issue by rotech** [Yubico/pam-u2f#282]
Ubuntu 22.10
libpam-u2f version 1.1.0-1.1build1

/dev/hidraw4: vendor=0x1050, product=0x0402 (Yubico YubiKey FIDO)

When using the following configuration, the terminal prints "Please touch device", but the green light does not come on, and there is no wait period, it fails immediately.
`auth required pam_u2f.so cue`

However if I use the configuration below, I am asked for the PIN first, then the "Please touch the device" prompt comes up, the light comes on, I touch the sensor and everything works perfectly.
`auth required pam_u2f.so cue pinverification=1`

Debug message from the failure:
debug(pam_u2f): util.c:1069 (get_authenticators): Checking whether key exists in authenticator 0
debug(pam_u2f): util.c:1079 (get_authenticators): Authenticator path: /dev/hidraw4
debug(pam_u2f): util.c:1106 (get_authenticators): Found key in authenticator 0
debug(pam_u2f): pam-u2f.c:434 (pam_sm_authenticate): do_authentication returned -2
debug(pam_u2f): pam-u2f.c:473 (pam_sm_authenticate): done. [Authentication failure]

**Comment by LDVG** [comment]
Hi,

Could you please install `fido2-tools` and provide the output of `fido-token -I /dev/hidraw4`?

Thank you.

**Comment by rotech** [comment]
```
proto: 0x02
major: 0x05
minor: 0x05
build: 0x06
caps: 0x05 (wink, cbor, msg)
version strings: FIDO_2_0, FIDO_2_1_PRE, FIDO_2_1
extension strings: credProtect, hmac-secret, largeBlobKey, credBlob, minPinLength
transport strings: usb
algorithms: es256 (public-key), eddsa (public-key)
aaguid: d8522d9f575b486688a9ba99fa02f35b
options: rk, up, nouv, noplat, uvToken, alwaysUv, credMgmt, authnrCfg, nobioEnroll, clientPin, largeBlobs, pinUvAuthToken, setMinPINLength, nomakeCredUvNotRqd, credentialMgmtPreview, nouserVerificationMgmtPreview
maxmsgsiz: 1200
maxcredcntlst: 8
maxcredlen: 128
maxlargeblob: 1024
fwversion: 0x50506
pin protocols: 2, 1
pin retries: 8
uv retries: undefined
sensor type: 1 (touch)
max samples: 16
```

**Comment by LDVG** [comment]
Thanks!

This looks like a YubiKey Bio with:
-  a PIN set (`options` reports [`clientPin`](https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#getinfo-clientpin));
- no fingerprints enrolled (`options` reports [`nouv`](https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#getinfo-uv)); and
- the [`alwaysUv`](https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#getinfo-alwaysuv) option enabled. 

Since your authenticator is configured to always require some form of user verification, and no fingerprints are enrolled, a PIN is required to get an assertion.

If you want to use your authenticator without a PIN, you need to either enroll at least one fingerprint, or disable the `alwaysUv` option. If you choose the latter, you are dependent on Relying Parties requesting user verification to protect your credentials.

**Comment by rotech** [comment]
Ah, that all makes sense now. Thank you.
