### ISSUE TITLE
Wait for device too

### ISSUE THREAD

**Issue by gdamjan** [Yubico/pam-u2f#57]
I have `auth required pam_u2f.so cue` in `/etc/pam.d/sudo`

When the Yubikey is not plugged in, the "Please touch the device." message doesn't appear, and access is denied. Can it instead wait for the device to be plugged? Either by using udev to notify it for a new device, or just busy-loop polling?

**Comment by thorduri** [comment]
The `cue` parameter is to remind you to touch the device for the authentication to take place.

`interactive` is to prompt (if no devices are found) and wait for a device to be inserted, so you might
want something along the lines of:

`auth required pam_u2f.so cue interactive`

I'll look into clarifying the documentation.

**Comment by gdamjan** [comment]
I've tried that combination, and it's a bit annoying to have to press ENTER when it could theoretically find out that by itself

**Comment by Cysioland** [comment]
Same here.

**Comment by LinuxOnTheDesktop** [comment]
Similarly, consider the following. At present, on Linux, at the login screen, if login fails because the Yubikey is not inserted, one gets the message 'invalid password' (or whatever similar message, to that effect, the installed login manager generates upon authentication failure). But an invalid password is not the problem. The lack of the physical key is the problem. So the user being told the real problem - at least if he/she has set some config flag, earlier - would be good. 

Note also that at present, at least on my system, two-factor authentication with Yubikey, at login, does not work properly anyway (= #137).
